### PR TITLE
V1.0

### PR DESCRIPTION
**Pull request by Lukyio**

### CODE REVIEW

**Review by guyts96 — APPROVED** [review]

**Review by Plantin7 — APPROVED** [review]
👎 👎 👎 👎 👎

**Review by souziel — APPROVED** [review]

**Review by asoran — APPROVED** [review]
🤪
There’s no reason a fake can’t do what the real thing would. And it’s possible for a fake to be more real than the real thing
The fake is of far greater value. In its deliberate attempt to be real, it's more real than the real thing.

**Review by an-desco — APPROVED** [review]
💯

**Comment by Lukyio** [comment]
> 
> 
> 🤪
> There’s no reason a fake can’t do what the real thing would. And it’s possible for a fake to be more real than the real thing
> The fake is of far greater value. In its deliberate attempt to be real, it's more real than the real thing.

Are you real ?

**Pull request merged**
